### PR TITLE
Added support for authorizers.

### PR DESCRIPTION
**Pull request by braindx**
Resolves issue #4

### CODE REVIEW

**Comment by eahefnawy** [comment]
sweet stuff @braindx !! thanks for that! Could you maybe add an example serverless.yml with authorizer usage based on your changes? Would love to test this end to end before merging! 🙌

**Comment by lolcoolkat** [comment]
Really wish custom authorizers weren't only supported on the $connect route :( Should be able to connect to the websocket and then authorize on any route we specify!

**Comment by braindx** [comment]
AWS only supports authorizers on the $connect route as that's the only route with HTTP headers and query strings. Beyond that, you're obviously free to specify whatever credentials you need per-request and handle them in your Lambda function.

**Comment by waynerobinson** [comment]
This looks great for initial testing of this before proper CloudFormation support.

Although, can I confirm that this deletes the authorizer on every deploy?

**Comment by jslowack** [comment]
Super nice! Any idea when this is going to published to npm?

**Comment by eahefnawy** [comment]
@jslowack Just wrapping couple of more fixes, then we'll release! 😊

**Comment by tkbrady** [comment]
This seems to address custom authorizers; however are AWS_IAM authorizers also supported?

**Comment by braindx** [comment]
That's correct. Only custom authorizers are supported with this change. Maybe a new issue should be opened?

**Comment by simon-ye** [comment]
hey @jslowack any idea when we can push this to npm?

**Pull request merged**
