### PR TITLE
Adding a catch block to the deleteIntegration request

### PR DESCRIPTION
**Pull request by lolcoolkat**
When deploying routes via different services, you may end up with an error like the following. This catch block will catch this error and just move on to the next route.

Error

### CODE REVIEW

**Comment by eahefnawy** [comment]
hmm that's interesting. All API routes should be cleared! @lolcoolkat are all your services sharing the same APIG? 🤔

**Comment by eahefnawy** [comment]
@lolcoolkat yep I can see that, but since each service has its own API ID, all routes should be cleared automatically, unless all your services are sharing the same API, that's why I'm asking if that's your case?

**Comment by lolcoolkat** [comment]
Yes all of my services are sharing the same API :)

**Comment by eahefnawy** [comment]
@lolcoolkat if I'm not mistaken, the only way we'd receive this error is if we're not clearing all routes by default like we're doing, is that correct?

Based on my understanding, you've modified the plugin by not clearing all the routes to fit your usecase, and as a result you're seeing this error which this PR fixes.

If that's the case, it seems that this PR solves a problem that is not caused by this codebase to begin with, and I suggest you keep that fix in your own codebase along with the other changes that caused this issue.

Just wanna avoid code debt and unexpected issues.

**Comment by eahefnawy** [comment]
Thanks for understanding @lolcoolkat 🙌 ... you got an interesting use case there.

**Pull request closed without merging**
